"""
Global configuration constants for the 'pack' cryptographic layers.
"""

# === Layer 1 Constants ===
DEFAULT_NUM_BALLS = 300
DEFAULT_SIM_FRAMES = 2000
DEFAULT_BALL_DIM = 256
DEFAULT_PBKDF2_ITERS = 200_000
DEFAULT_RADIUS = 5
DEFAULT_HISTORY_BALLS = 10

SCREEN_WIDTH_MIN = 640
SCREEN_WIDTH_MAX = 1920
SCREEN_HEIGHT_MIN = 480
SCREEN_HEIGHT_MAX = 1200

PULSE_AMPLITUDE = 100
PULSE_FREQUENCY = 1.0
SPEED_LIMIT = 30.0

CHAOS_MIN = 0.07
CHAOS_MAX = 0.93
CHAOS_NOISE_RANGE = 0.008

# === Layer 2 Constants ===
L2_POLY_DEGREE = 256
L2_MODULUS_Q = 3329
L2_ETA = 2
L2_K = 2
L2_COMPRESSION_BITS = 10

# Redundancies and message limits
CHECKSUM_LEN = 4
ECC_REDUNDANCY = 8
REP = 3
MAX_MESSAGE_BYTES = L2_POLY_DEGREE // REP - CHECKSUM_LEN - ECC_REDUNDANCY

# Optional flags
USE_KYBER_NTT = False

# Package metadata
PACKAGE_NAME = "pack"
PACKAGE_VERSION = "1.0.0"
PACKAGE_AUTHOR = "VikRAM_64GB"
